### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by markuszeller** [dotheflopboy/Aseprite-German-Translation#6]
Since the latest updates some translations are missing.

I've created a branch for that purpose in my fork and wrote a little script to find which [keys are missing](https://github.com/markuszeller/Aseprite-German-Translation/blob/diff-from-original/diff-missing-de.ini) into it.

**Comment by inxomnyaa** [comment]
I've been working on official translations and just now was sent this repo. I'll use this repo as a guide i guess. As for the missing translations, i think i might have already covered some of them
https://hosted.weblate.org/translate/aseprite/aseprite/de/?sort_by=-priority%2Cposition&offset=533

**Comment by inxomnyaa** [comment]
It looks like this repo was actually automatically translated via some tool. Things such as "Brush" are sometimes randomly translated as "Bürste" (scrubbing brush) instead of "Pinsel" (paint brush)

**Comment by markuszeller** [comment]
Oh nice. I did not know there's a official translation (tool). Via the help I came here to this repo.

**Comment by inxomnyaa** [comment]
I've completed the translation on Weblate https://hosted.weblate.org/download/aseprite/aseprite/de/
It can be downloaded via "Files" > "Download translation" (but i haven't found a way to import it yet)
![image](https://github.com/dotheflopboy/Aseprite-German-Translation/assets/8733998/8a29a95c-645a-4170-8002-c5c8875ecfb5)

**Comment by inxomnyaa** [comment]
Appears that the Weblate translations aren't supported by Aseprite at the moment: https://github.com/aseprite/languages/issues/30 😅

**Comment by markuszeller** [comment]
When I download the ini file and rename it to `de.ini` and replace with that in this zip file it works for me. IMHO you may close this issue.

**Comment by inxomnyaa** [comment]
I've tried just this since i wanted to provide a temporary zip file, but it didn't change anything, even after a restart 🤔 You sure the old version isn't cached in the /extensions folder?
But yeah i think in theory it should work, it would just print out the newlines as \n

**Comment by inxomnyaa** [comment]
Well, my mistake, for some reason the package.json in the zip hasn't updated when i edited it
About closing the issue, since you made it you can actually close it as well
[aseprite-language-german.zip](https://github.com/dotheflopboy/Aseprite-German-Translation/files/13664880/aseprite-language-german.zip)

**Comment by markuszeller** [comment]
Yes, and verified again. As you confirm I'll close it now.

I suggest, you could create a pull request with updated de.ini file and add the weblate URL to the readme.md. Then this repo can directly used as before for all other users.

Thanks for your effort.
